### PR TITLE
UXUI-195 add reactify to browserify.transform field

### PR DESCRIPTION
**Pull request by jackdcrawford**
#### What does this PR do?
Adds `reactify` as a [browserify.transform](https://github.com/substack/browserify-handbook#browserifytransform-field) field so that generated modules are also transformed when included as a dependency (e.g. in the `ui-toolkit`).

#### What unit or integration tests does this PR have?
N/A

#### What selenium tests does this PR have?
N/A

#### How should a developer review this?
Check the code & then run the manual testing steps below

#### How should this be manually tested?
1. Switch to this branch
2. `npm install`
3. `npm install -g .` to globally install this generator
4. Create a test directory somewhere on your machine & change to that directory
5. `yo ui-component` & fill out the prompts with `test`
6. Open the generated `package.json`, you should see:
```json
"browserify": {
  "transform": ["reactify"]
},
```

#### Any background context you want to provide?
This removes the requirement of globally transforming all dependencies (which has exceeded the ulimit on some machines). 

#### What are the relevant tickets?
[UXUI-195](https://holidayextras.jira.com/browse/UXUI-195)

#### Screenshots (if appropriate)
N/A

#### What gif best describes how you feel about this work?
lulz

---
#### Quality checklist (for PR author to complete BEFORE code review):
- [x] I've checked there is appropriate unit test coverage.
- [x] I've checked there is appropriate selenium test coverage.
- [x] I've included regression tests for any bug fixes.
- [x] I've updated documentation with any changes to procedures.
- [x] I've tested this on mobile Android, Safari, Chrome for any visual changes.
- [x] I've tested this on desktop IE9/10/11, Firefox, Chrome for any visual changes.
- [x] I've checked any significant visual changes with a member of the UX/UI pod.
- [x] I've checked this work against the requirements of the Jira.
- [x] I've added and updated translations for all supported languages
- [x] I've informed those who need to know of any unforeseen impact of this work (database migrations, deployment procedure changes).
- [x] I am ready for this to be code reviewed, merged and tested.
- [x] I've thought about writing a blog post about this

#### IP or Developer Review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] +1 from me!

#### Software Engineer or Developer review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked for coding anti-patterns.
- [x] I've checked this work against the requirements of the Jira.
- [x] +1 from me!

#### Software Engineer or project guru review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked for coding anti-patterns.
- [x] I don’t believe this work introduces unnecessary technical debt.
- [x] +1 from me!

### CODE REVIEW

**Comment by HarleyRowland** [comment]
Taking IP review

**Comment by jodiedoubleday** [comment]
Taking SE review

**Comment by jodiedoubleday** [comment]
I see
```
  "browserify": {
    "transform": [
      "reactify"
    ]
  },
```
so :+1: from me

**Comment by HarleyRowland** [comment]
:+1:

**Comment by michaelcarter** [comment]
Taking SE/Dev

**Comment by michaelcarter** [comment]
I see the stuff in the thing.

I'd just double check with Luke that this is ok, I can't remember why we didn't do this to begin with but there might have been a reason. If it's going to cause problems the `ulimit` completely adjustable - OS X just has it set low by default.

**Pull request merged**
